drop table if exists tb_member cascade;

create table tb_member
(
  id           bigint generated by default as identity,
  email        varchar(255),
  username     varchar(255),
  password     varchar(255),
  created_date timestamp,
  primary key (id)
);
